spring.profiles.active: dv

---

spring:
  profiles: dv

info:
  app:
    name: quick-riders-discovery-server
    description: quick riders discovery server for micro services
    version: 0.0.1

server:
  port: 8761

security:
  user:
    password: ${SECURITY_USER_PASSWORD:password}

eureka:
  instance:
    hostname: discovery-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    org:
      springframework: INFO

---

spring:
  profiles: st

server:
  port: 8761

eureka:
  instance:
    hostname: 127.0.1.1
    nonSecurePort: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    ROOT: WARN

---
spring:
  profiles: pd

eureka:
  instance:
    hostname: ${localhost.hostname:${localhost.ngrok}.ngrok.com}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:${security.user.password}@${PREFIX:}eureka.cfapps.io/eureka/

logging:
  level:
    ROOT: WARN